#!/bin/bash

# Check if Script is Run as user 
if [[ $EUID -ne 0 ]]; then  
  #Load special config 
  dconf load -f / < config/mint_eggs

  tar -xvzf config/config.tar.gz

  rm -R ~/.config
  mv -f .config/ ~

  #Begin of scripts 
  sudo ./script/install_begin

  dconf load -f / < config/mint_eggs

  #Install Qredshift 
  curl https://github.com/raphaelquintao/QRedshiftCinnamon/raw/master/install.sh -sSfL | bash 

  echo -ne "
-------------------------------------------------------------------------
                    Wait until the reboot ...
-------------------------------------------------------------------------
"&& sleep 20

  reboot

  else
    echo "You must be a non-root user to run this script, please run ./install" 2>&1
    exit 1
fi

