#!/bin/bash

util=$(getent passwd "1000"|cut -d: -f1)

#Change /etc/sudoers, allowing to use sudo without password
rm /etc/sudoers

chown root:root config/sudoers
chmod 440 config/sudoers
mv config/sudoers /etc/sudoers

# Lightdm Autologin 
rm /etc/lightdm/lightdm.conf
mv config/lightdm.conf /etc/lightdm/lightdm.conf

chown root:root config/lightdm.conf 
chmod 644 config/lightdm.conf 
echo "autologin-user=$util" >> /etc/lightdm/lightdm.conf

#Add policyKit (polkit) rules, allowing to use gtk root application without password
chown root:root config/disable-passwords.rules
chmod 644 config/disable-passwords.rules
mv config/disable-passwords.rules /etc/polkit-1/rules.d/disable-passwords.rules

#Plymouth configuration
unzip config/linux-mac-style.zip

mv linux-mac-style/ /usr/share/plymouth/themes/
update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/linux-mac-style/linux-mac-style.plymouth 200

#Remove mozilla configuration to replace with a new one 
rm -R /home/$util/.mozilla/

#Cleaning packages 
apt autoclean
apt clean
apt autoremove -y 
apt purge ~c -y 
