#!/bin/bash

# Check if Script is Run as Root
if [[ $EUID -ne 0 ]]; then
  echo "You must be a root user to run this script, please run sudo ./install_begin 2>&1"
  
  exit 1
  else

  apt update -y && apt upgrade -y 

  ./script/apt_install
  ./script/themes_and_grub_install
  ./script/config_install
  
fi



